### ISSUE TITLE
Tabs for files added through Git lose active styling

### ISSUE THREAD

**Issue by Gert-dev** [tjkohli/nebula-ui#7] opened 2017-01-29 19:49 UTC
Hello

Active tabs neatly light up to indicate their state via the `tab -active` class. However, it appears that when you have a tab open that has been added via Git, the highlight is lost; the tab title will be green and when such a tab is active, it will remain the same shade of green, losing the indication of being active.

It seems that, inside the `<li class="tab active">`, the `<div class="title">` becomes `<div class="title status-added">`, where the `status-added` class overrides the active styling's color. 

Just a minor issue, of course :).

Thanks in advance

**Comment by tjkohli** [comment] 2017-01-30 02:52
Hi @Gert-dev, is this issue related to a plugin? I do not see Git classes on my tabs.

**Comment by Gert-dev** [comment] 2017-01-30 08:07
Thanks for your response.

I think it's related to Atom's built-in support for Git and only happens if you have a valid Git repository active. When you then create a new file and add it via `git add`, Atom will highlight it in the tree view. They are highlighted green in the tree view as well as in the tabs.

I noticed the same happens for ignored files, where the class received is `status-ignored` and the item will be greyed out.

**Comment by tjkohli** [comment] 2017-01-30 21:05
Can you post screenshots? I'm getting the feeling this is by design.

**Comment by Gert-dev** [comment] 2017-01-31 07:44
Sure!

![screenshot](https://cloud.githubusercontent.com/assets/24809863/22456134/e360c9aa-e790-11e6-8275-d36ffd84ec4f.png)

In this screenshot:

* The first tab is a normal tab that is not active (styled).
* The second tab is a normal tab that is active (styled).
* The third tab is a file that was marked as modified by Atom (`status-modified`) as it is modified according to Git. Whether this tab is active is not visible: the yellow color is always the same.
* The fourth tab is a file that was marked as ignored by Atom (`status-ignored`) as it is in the ignore list according to Git. Whether this tab is active is not visible: it is always dark grey.
* The fifth tab is a file that was marked as new by Atom as it is a new file (`status-added`) according to Git. Whether this tab is active is not visible: the green color is always the same.

The problem with the last three is that the modifier classes define a color that takes precedence over the colors specified by this theme for the active tab.

**Comment by tjkohli** [comment] 2017-01-31 20:06
@Gert-dev This has been fixed and will be released in the next update.

**Comment by tjkohli** [comment] 2017-01-31 23:34
Fixed with 0.5.1!

**Closed by tjkohli** 2017-01-31 23:34 UTC
Labels: bug

**Comment by Gert-dev** [comment] 2017-02-01 16:18
Great, now I can finally properly see what tab is active 😄. However, I think you missed `status-ignored`, which overrides any color to be the same as an inactive tab :-).

Also: the active color is now white for every tab, even if it is modified. Currently you can no longer see that a tab is modified in Git if it's active (only if it's inactive, in which case it will be a dark green). Was it perhaps intentional that the color isn't green (but faded out) when inactive and green (full brightness) when active?

Thanks!
